//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int id { get; set; }
        public string name { get; set; }
        public string color { get; set; }
        public Nullable<int> power { get; set; }
        public Nullable<int> toughness { get; set; }
        public Nullable<int> cmc { get; set; }
        public string image { get; set; }
        public string type { get; set; }
        public string notes { get; set; }
        public string rarity { get; set; }
        public string set { get; set; }
    }
}
